#!/usr/bin/env python3
"""AgentShift GitHub Action — detect agent definitions and generate portability report."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

# Agent definition files and their corresponding --from platform
AGENT_FILE_MAP: dict[str, str] = {
    "AGENTS.md": "agents-md",
    "CLAUDE.md": "claude-code",
    "SKILL.md": "openclaw",
}

# Glob patterns for agent files that may appear in subdirectories
AGENT_GLOB_PATTERNS: dict[str, str] = {
    "*.agent.md": "copilot",
}


def find_agent_definitions(workspace: Path) -> list[tuple[Path, str, str]]:
    """Find agent definition files in the workspace.

    Returns list of (path, platform, display_name) tuples.
    """
    agents: list[tuple[Path, str, str]] = []

    # Check root-level known files
    for filename, platform in AGENT_FILE_MAP.items():
        filepath = workspace / filename
        if filepath.exists():
            agents.append((filepath.parent, platform, filename))

    # Search for .agent.md files (Copilot agents)
    for pattern, platform in AGENT_GLOB_PATTERNS.items():
        for match in workspace.rglob(pattern):
            # Skip node_modules, .git, etc.
            if any(part.startswith(".") or part == "node_modules" for part in match.parts):
                continue
            agents.append((match, platform, match.name))

    # Check for SKILL.md in subdirectories (openclaw skills)
    for subdir in workspace.iterdir():
        if not subdir.is_dir() or subdir.name.startswith("."):
            continue
        skill_md = subdir / "SKILL.md"
        if skill_md.exists() and subdir != workspace:
            agents.append((subdir, "openclaw", f"{subdir.name}/SKILL.md"))

    return agents


def run_diff(source: Path, platform: str, targets: str) -> dict | None:
    """Run agentshift diff --output-format json and return parsed JSON."""
    cmd = [
        sys.executable,
        "-m",
        "agentshift",
        "diff",
        str(source),
        "--from",
        platform,
        "--targets",
        targets,
        "--output-format",
        "json",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode != 0:
            print(f"Warning: diff failed for {source}: {result.stderr}", file=sys.stderr)
            return None
        return json.loads(result.stdout)
    except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError) as e:
        print(f"Warning: diff error for {source}: {e}", file=sys.stderr)
        return None


def generate_report(results: list[tuple[str, dict]], targets_list: list[str]) -> str:
    """Generate markdown report from diff results."""
    lines: list[str] = []
    lines.append("## AgentShift Portability Report\n")
    lines.append(f"Found **{len(results)} agent definition{'s' if len(results) != 1 else ''}** in this repository.\n")

    # Build table header
    header = "| Agent | Source |"
    separator = "|---|---|"
    for t in targets_list:
        header += f" {t} |"
        separator += "---|"
    lines.append(header)
    lines.append(separator)

    all_scores: list[int] = []
    notes: list[str] = []

    for display_name, data in results:
        source_platform = data.get("source_platform", "unknown")
        scores = data.get("scores", {})
        row = f"| {display_name} | {source_platform} |"
        for t in targets_list:
            score = scores.get(t)
            if score is not None:
                all_scores.append(score)
                row += f" {score}% |"
            else:
                row += " — |"
        lines.append(row)

        # Collect notes about dropped components
        for comp in data.get("components", []):
            for t in targets_list:
                if comp.get(t) == "none" and comp.get("source"):
                    notes.append(
                        f"{comp['name']} has no native {t} equivalent."
                    )

    avg = int(sum(all_scores) / len(all_scores)) if all_scores else 0
    lines.append(f"\n**Average portability: {avg}%**\n")

    if notes:
        lines.append("<details><summary>What this means</summary>\n")
        # Deduplicate and limit notes
        for note in sorted(set(notes))[:10]:
            lines.append(f"- {note}")
        lines.append(f"\nLearn more: [agentshift.sh](https://agentshift.sh)")
        lines.append("</details>\n")

    try:
        import agentshift

        version = agentshift.__version__
    except ImportError:
        version = "unknown"

    lines.append(f"_Generated by [AgentShift](https://agentshift.sh) v{version}_")

    return "\n".join(lines)


def main() -> None:
    workspace = Path(os.environ.get("GITHUB_WORKSPACE", ".")).resolve()
    targets = os.environ.get("TARGETS", "claude-code,copilot,bedrock,m365,vertex")
    targets_list = [t.strip() for t in targets.split(",") if t.strip()]

    print(f"Scanning {workspace} for agent definitions...")
    agents = find_agent_definitions(workspace)

    if not agents:
        print("No agent definitions found. Skipping report.")
        # Set output even when no agents found
        github_output = os.environ.get("GITHUB_OUTPUT")
        if github_output:
            with open(github_output, "a") as f:
                f.write("average-score=0\n")
        return

    print(f"Found {len(agents)} agent definition(s):")
    for path, platform, name in agents:
        print(f"  - {name} ({platform})")

    results: list[tuple[str, dict]] = []
    for path, platform, display_name in agents:
        data = run_diff(path, platform, targets)
        if data:
            results.append((display_name, data))

    if not results:
        print("No successful analyses. Skipping report.")
        return

    report = generate_report(results, targets_list)

    # Write report file
    report_path = workspace / "agentshift-report.md"
    report_path.write_text(report, encoding="utf-8")
    print(f"Report written to {report_path}")

    # Calculate average score
    all_scores = []
    for _, data in results:
        for score in data.get("scores", {}).values():
            all_scores.append(score)
    avg = int(sum(all_scores) / len(all_scores)) if all_scores else 0

    # Set GitHub Action output
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"average-score={avg}\n")

    print(f"Average portability score: {avg}%")


if __name__ == "__main__":
    main()
