"""CrewAI emitter — converts AgentShift IR into a CrewAI project with YAML configs.

Produces:
  config/agents.yaml — Agent definitions (role, goal, backstory)
  config/tasks.yaml  — Task definitions
  crew.py            — @CrewBase class wiring agents and tasks
  requirements.txt   — crewai + tool deps
  README.md          — Setup and usage instructions
"""

from __future__ import annotations

import re
from pathlib import Path

from agentshift.ir import AgentIR

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit(ir: AgentIR, output_dir: Path) -> None:
    """Write a CrewAI project from an AgentIR."""
    output_dir.mkdir(parents=True, exist_ok=True)
    config_dir = output_dir / "config"
    config_dir.mkdir(parents=True, exist_ok=True)

    _write_agents_yaml(ir, config_dir)
    _write_tasks_yaml(ir, config_dir)
    _write_crew_py(ir, output_dir)
    _write_requirements_txt(ir, output_dir)
    _write_readme(ir, output_dir)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _snake(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    s = re.sub(r"^[^a-zA-Z]+", "", s) or "agent"
    return s.lower()


def _pascal(name: str) -> str:
    parts = re.split(r"[^a-zA-Z0-9]+", name)
    return "".join(p.capitalize() for p in parts if p)


def _yaml_block(text: str, indent: int = 4) -> str:
    """Format text as a YAML block scalar with proper indentation."""
    prefix = " " * indent
    cleaned = text.strip().replace("\n", f"\n{prefix}")
    return cleaned


def _first_sentence(text: str) -> str:
    """Extract the first sentence from text."""
    match = re.match(r"^(.+?[.!?])\s", text)
    if match:
        return match.group(1)
    # If no sentence boundary, take first 200 chars
    return text[:200].strip()


def _tool_names(ir: AgentIR) -> list[str]:
    """Return tool names that are emittable for CrewAI."""
    return [t.name for t in ir.tools if t.kind not in ("builtin",)]


# ---------------------------------------------------------------------------
# config/agents.yaml
# ---------------------------------------------------------------------------


def _write_agents_yaml(ir: AgentIR, config_dir: Path) -> None:
    agent_key = _snake(ir.name)

    # Derive role, goal, backstory from IR
    system_prompt = ir.persona.system_prompt or ir.description or ""
    role = ir.description[:80] if ir.description else _first_sentence(system_prompt)
    goal = _first_sentence(system_prompt) if system_prompt else ir.description or ""
    backstory = system_prompt

    lines: list[str] = [
        "# Generated by AgentShift — CrewAI agents config",
        f"{agent_key}:",
        "  role: >",
        f"    {_yaml_block(role, 4)}",
        "  goal: >",
        f"    {_yaml_block(goal, 4)}",
        "  backstory: >",
        f"    {_yaml_block(backstory, 4)}",
        "  verbose: true",
    ]

    # Model
    model = ir.metadata.platform_extensions.get("crewai", {}).get("model", "gpt-4o")
    lines.append(f"  llm: {model}")

    # Tool names (informational — tools are wired in crew.py)
    tools = _tool_names(ir)
    if tools:
        tool_list = ", ".join(tools)
        lines.append(f"  # tools: [{tool_list}]")

    lines.append("")

    (config_dir / "agents.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# config/tasks.yaml
# ---------------------------------------------------------------------------


def _write_tasks_yaml(ir: AgentIR, config_dir: Path) -> None:
    agent_key = _snake(ir.name)

    lines: list[str] = [
        "# Generated by AgentShift — CrewAI tasks config",
    ]

    # Create tasks from triggers, or a default main_task
    manual_triggers = [t for t in ir.triggers if t.kind == "manual"]

    if manual_triggers:
        for i, trig in enumerate(manual_triggers):
            task_key = f"task_{i + 1}" if len(manual_triggers) > 1 else "main_task"
            desc = trig.message or ir.description
            lines.extend(
                [
                    f"{task_key}:",
                    "  description: >",
                    f"    {_yaml_block(desc, 4)}",
                    "  expected_output: >",
                    "    Task completed successfully",
                    f"  agent: {agent_key}",
                    "",
                ]
            )
    else:
        lines.extend(
            [
                "main_task:",
                "  description: >",
                f"    {_yaml_block(ir.description, 4)}",
                "  expected_output: >",
                "    Task completed successfully",
                f"  agent: {agent_key}",
                "",
            ]
        )

    (config_dir / "tasks.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# crew.py
# ---------------------------------------------------------------------------


def _write_crew_py(ir: AgentIR, output_dir: Path) -> None:
    agent_key = _snake(ir.name)
    class_name = _pascal(ir.name)

    lines: list[str] = [
        f'"""{ir.name} — CrewAI crew. Generated by AgentShift."""',
        "",
        "from crewai import Agent, Crew, Process, Task",
        "from crewai.project import CrewBase, agent, crew, task",
        "",
        "",
        "@CrewBase",
        f"class {class_name}Crew:",
        '    agents_config = "config/agents.yaml"',
        '    tasks_config = "config/tasks.yaml"',
        "",
        "    @agent",
        f"    def {agent_key}(self) -> Agent:",
        "        return Agent(",
        f'            config=self.agents_config["{agent_key}"],',
    ]

    tools = _tool_names(ir)
    if tools:
        lines.append("            tools=[],  # TODO [agentshift]: wire tool instances")
    lines.extend(
        [
            "        )",
            "",
            "    @task",
            "    def main_task(self) -> Task:",
            '        return Task(config=self.tasks_config["main_task"])',
            "",
            "    @crew",
            "    def crew(self) -> Crew:",
            "        return Crew(",
            "            agents=self.agents,",
            "            tasks=self.tasks,",
            "            process=Process.sequential,",
            "            verbose=True,",
            "        )",
            "",
        ]
    )

    (output_dir / "crew.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------


def _write_requirements_txt(ir: AgentIR, output_dir: Path) -> None:
    lines: list[str] = [
        "# Generated by AgentShift — CrewAI emitter",
        f"# Agent: {ir.name}",
        "",
        "crewai>=0.1.0",
        "",
    ]

    (output_dir / "requirements.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# README.md
# ---------------------------------------------------------------------------


def _write_readme(ir: AgentIR, output_dir: Path) -> None:
    source = ir.metadata.source_platform or "unknown"
    class_name = _pascal(ir.name)

    lines: list[str] = [
        f"# {ir.name} — CrewAI Crew",
        "",
        f"> {ir.description}",
        "",
        f"> Generated by [AgentShift](https://github.com/agentshift/agentshift) from {source}.",
        "",
        "## Setup",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "export OPENAI_API_KEY=your-key-here",
        "```",
        "",
        "## Run",
        "",
        "```python",
        f"from crew import {class_name}Crew",
        "",
        f'result = {class_name}Crew().crew().kickoff(inputs={{"topic": "example"}})',
        "print(result)",
        "```",
        "",
        "## Files",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| `config/agents.yaml` | Agent role, goal, and backstory |",
        "| `config/tasks.yaml` | Task descriptions and expected outputs |",
        "| `crew.py` | `@CrewBase` class wiring agents + tasks |",
        "| `requirements.txt` | Python dependencies |",
        "| `README.md` | This file |",
        "",
        "## About",
        "",
        "This crew was automatically generated by **AgentShift**.",
        "",
        f"- **Source format:** {source}",
        "- **Target format:** CrewAI",
        "",
    ]

    (output_dir / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
