"""OpenAI Agents SDK emitter — converts AgentShift IR into a ready-to-run Python package.

Produces:
  agent.py         — Agent definition with instructions + tools
  tools.py         — @function_tool-decorated stubs for each IR tool
  runner.py        — Async runner entry point
  requirements.txt — openai-agents + optional deps
  README.md        — Setup and usage instructions
"""

from __future__ import annotations

import re
from pathlib import Path

from agentshift.ir import AgentIR, Tool

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit(ir: AgentIR, output_dir: Path) -> None:
    """Write an OpenAI Agents SDK package from an AgentIR."""
    output_dir.mkdir(parents=True, exist_ok=True)

    _write_tools_py(ir, output_dir)
    _write_agent_py(ir, output_dir)
    _write_runner_py(ir, output_dir)
    _write_requirements_txt(ir, output_dir)
    _write_readme(ir, output_dir)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _snake(name: str) -> str:
    """Convert a name to a valid Python snake_case identifier."""
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    s = re.sub(r"^[^a-zA-Z]+", "", s) or "agent"
    return s.lower()


def _slug(name: str) -> str:
    """Lowercase hyphen-separated slug."""
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "agent"


def _json_type_to_py(json_type: str) -> str:
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }.get(json_type, "str")


def _tool_fn_name(tool: Tool) -> str:
    return _snake(tool.name)


def _is_emittable(tool: Tool) -> bool:
    """Return True if the tool should produce code in tools.py."""
    return tool.kind != "builtin"


def _has_mcp_tools(ir: AgentIR) -> bool:
    return any(t.kind == "mcp" for t in ir.tools)


# ---------------------------------------------------------------------------
# tools.py
# ---------------------------------------------------------------------------


def _write_tools_py(ir: AgentIR, output_dir: Path) -> None:
    lines: list[str] = []
    lines.append(f'"""Tool stubs for {ir.name} — generated by AgentShift."""')
    lines.append("")

    needs_subprocess = any(t.kind == "shell" for t in ir.tools)
    has_mcp = _has_mcp_tools(ir)

    lines.append("from agents import function_tool")
    if has_mcp:
        lines.append("from agents.mcp import MCPServerStdio")
    lines.append("")

    if needs_subprocess:
        lines.append("import subprocess")
        lines.append("")

    # MCP server configs
    mcp_vars: list[str] = []
    for t in ir.tools:
        if t.kind == "mcp":
            var = f"mcp_{_snake(t.name)}"
            mcp_vars.append(var)
            endpoint = t.endpoint or ""
            lines.append(f"# MCP server for {t.name}")
            lines.append("# TODO [agentshift]: Configure MCP server endpoint")
            lines.append(f"{var} = MCPServerStdio(")
            lines.append(f'    name="{t.name}",')
            lines.append(
                f'    params={{"command": "npx", "args": ["-y", "{endpoint or t.name}"]}},'
            )
            lines.append(")")
            lines.append("")

    # Function tools
    for t in ir.tools:
        if not _is_emittable(t) or t.kind == "mcp":
            continue

        fn = _tool_fn_name(t)

        if t.kind == "shell":
            # Shell tool stub with subprocess
            lines.append("")
            lines.append("@function_tool")
            lines.append(f"def {fn}(command: str, args: list[str] = []) -> str:")
            desc = t.description or f"Run {t.name} commands."
            lines.append(f'    """{desc} Generated by AgentShift — implement real logic here."""')
            lines.append("    # TODO [agentshift]: Replace with real implementation")
            lines.append(
                f'    result = subprocess.run(["{t.name}", command, *args], capture_output=True, text=True)'
            )
            lines.append("    return result.stdout or result.stderr")
            lines.append("")

        elif t.kind == "function":
            # Function tool stub with typed params
            props = (t.parameters or {}).get("properties", {}) if t.parameters else {}
            required = (t.parameters or {}).get("required", []) if t.parameters else []

            sig_parts: list[str] = []
            for pname, pinfo in props.items():
                ptype = _json_type_to_py(
                    pinfo.get("type", "string") if isinstance(pinfo, dict) else "string"
                )
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} | None = None")

            if not sig_parts:
                sig_parts = ["input: str"]

            sig = ", ".join(sig_parts)
            lines.append("")
            lines.append("@function_tool")
            lines.append(f"def {fn}({sig}) -> str:")
            desc = t.description or f"Call the {t.name} tool."
            lines.append(f'    """{desc}"""')
            lines.append("    # TODO [agentshift]: implement")
            lines.append(f'    raise NotImplementedError("{t.name} is not yet implemented")')
            lines.append("")

        else:
            # Unknown / openapi — generic stub
            lines.append("")
            lines.append("@function_tool")
            lines.append(f"def {fn}(input: str) -> str:")
            desc = t.description or f"Call the {t.name} tool."
            lines.append(f'    """{desc}"""')
            lines.append(f"    # TODO [agentshift]: implement '{t.name}' ({t.kind})")
            lines.append(f'    raise NotImplementedError("{t.name} is not yet implemented")')
            lines.append("")

    (output_dir / "tools.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# agent.py
# ---------------------------------------------------------------------------


def _write_agent_py(ir: AgentIR, output_dir: Path) -> None:
    agent_var = _snake(ir.name) + "_agent"

    # Collect tool imports
    fn_tools = [_tool_fn_name(t) for t in ir.tools if _is_emittable(t) and t.kind != "mcp"]

    lines: list[str] = []
    lines.append(f'"""{ir.name} — OpenAI Agents SDK agent. Generated by AgentShift."""')
    lines.append("")
    lines.append("from agents import Agent")

    if fn_tools:
        imports = ", ".join(fn_tools)
        lines.append(f"from .tools import {imports}")

    mcp_vars: list[str] = []
    if _has_mcp_tools(ir):
        for t in ir.tools:
            if t.kind == "mcp":
                mcp_vars.append(f"mcp_{_snake(t.name)}")
        mcp_imports = ", ".join(mcp_vars)
        lines.append(f"from .tools import {mcp_imports}")

    lines.append("")

    # Build system prompt
    system_prompt = ""
    if ir.persona.system_prompt:
        system_prompt = ir.persona.system_prompt.strip()
    elif ir.description:
        system_prompt = ir.description.strip()

    # Add guardrails to prompt
    suffix_parts: list[str] = []
    for g in ir.constraints.guardrails:
        suffix_parts.append(f"- {g}")
    for topic in ir.constraints.topic_restrictions:
        suffix_parts.append(f"- Do not discuss: {topic}")
    if suffix_parts:
        rules = "\n".join(suffix_parts)
        system_prompt = f"{system_prompt}\n\n## Rules\n{rules}" if system_prompt else rules

    escaped = system_prompt.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')

    lines.append(f"{agent_var} = Agent(")
    lines.append(f'    name="{ir.name}",')
    lines.append(f'    instructions="""{escaped}""",')

    if fn_tools:
        tool_list = ", ".join(fn_tools)
        lines.append(f"    tools=[{tool_list}],")

    if mcp_vars:
        mcp_list = ", ".join(mcp_vars)
        lines.append(f"    mcp_servers=[{mcp_list}],")

    model = ir.metadata.platform_extensions.get("openai-agents", {}).get("model", "gpt-4o")
    lines.append(f'    model="{model}",')
    lines.append(")")
    lines.append("")

    (output_dir / "agent.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# runner.py
# ---------------------------------------------------------------------------


def _write_runner_py(ir: AgentIR, output_dir: Path) -> None:
    agent_var = _snake(ir.name) + "_agent"

    lines: list[str] = []
    lines.append(f'"""Run {ir.name} agent."""')
    lines.append("")
    lines.append("import asyncio")
    lines.append("")
    lines.append("from agents import Runner")
    lines.append(f"from .agent import {agent_var}")
    lines.append("")
    lines.append("")
    lines.append("async def main():")
    lines.append("    result = await Runner.run(" + agent_var + ', input("You: "))')
    lines.append("    print(result.final_output)")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    asyncio.run(main())")
    lines.append("")

    (output_dir / "runner.py").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------


def _write_requirements_txt(ir: AgentIR, output_dir: Path) -> None:
    lines: list[str] = [
        "# Generated by AgentShift — OpenAI Agents SDK emitter",
        f"# Agent: {ir.name}",
        "",
        "openai-agents>=0.0.1",
    ]

    if _has_mcp_tools(ir):
        lines.append("mcp>=1.0.0")

    lines.append("")

    (output_dir / "requirements.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# README.md
# ---------------------------------------------------------------------------


def _write_readme(ir: AgentIR, output_dir: Path) -> None:
    source = ir.metadata.source_platform or "unknown"

    lines: list[str] = [
        f"# {ir.name} — OpenAI Agents SDK",
        "",
        f"> {ir.description}",
        "",
        f"> Generated by [AgentShift](https://github.com/agentshift/agentshift) from {source}.",
        "",
        "## Setup",
        "",
        "```bash",
        "pip install -r requirements.txt",
        "export OPENAI_API_KEY=your-key-here",
        "```",
        "",
        "## Run",
        "",
        "```bash",
        "python -m runner",
        "```",
        "",
        "## Files",
        "",
        "| File | Description |",
        "|------|-------------|",
        "| `agent.py` | Agent definition with instructions and tools |",
        "| `tools.py` | `@function_tool`-decorated tool stubs |",
        "| `runner.py` | Async runner entry point |",
        "| `requirements.txt` | Python dependencies |",
        "| `README.md` | This file |",
        "",
        "## About",
        "",
        "This agent was automatically generated by **AgentShift**.",
        "",
        f"- **Source format:** {source}",
        "- **Target format:** OpenAI Agents SDK",
        "",
    ]

    # Tool notes
    tools = [t for t in ir.tools if _is_emittable(t)]
    if tools:
        lines.append("## Tools")
        lines.append("")
        for t in tools:
            lines.append(f"- **{t.name}** ({t.kind}): {t.description or 'No description'}")
        lines.append("")

    # Trigger notes
    non_manual = [t for t in ir.triggers if t.kind != "manual"]
    if non_manual:
        lines.append("## Triggers")
        lines.append("")
        lines.append("The OpenAI Agents SDK has no native trigger system.")
        lines.append("Configure these triggers externally:")
        lines.append("")
        for trig in non_manual:
            expr = trig.cron_expr or trig.every or trig.webhook_path or trig.event_name or "?"
            lines.append(f"- **{trig.kind}** (`{trig.id or 'unnamed'}`): `{expr}`")
        lines.append("")

    (output_dir / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
